name: Build phone-caster & car-receiver APKs
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - uses: actions/checkout@v4

      - name: List repo root (debug)
        run: |
          echo "== REPO ROOT =="
          ls -la

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 1) 自动寻找仓库根目录的 ZIP（任意名字），优先取第一个
      - name: Locate project ZIP
        id: zip
        shell: bash
        run: |
          set -e
          ZIP=$(find . -maxdepth 1 -type f -name "*.zip" | head -n1 || true)
          if [ -z "$ZIP" ]; then
            echo "❌ 根目录没有找到 .zip 文件，请把源码压缩包放到仓库根目录再试"; exit 1
          fi
          echo "Using ZIP: $ZIP"
          echo "ZIP=$ZIP" | tee -a $GITHUB_OUTPUT

      # 2) 解压 ZIP
      - name: Unzip project ZIP
        run: |
          set -e
          unzip -q "${{ steps.zip.outputs.ZIP }}" -d srczip
          echo "== Unzipped to srczip =="
          find srczip -maxdepth 3 -type d -printf "%p\n"

      # 3) 自动识别两个 Android 工程（含 gradlew 且含 app/build.gradle*）
      - name: Detect Android projects in ZIP
        id: detect
        shell: bash
        run: |
          set -e
          mapfile -t PROJ < <(find srczip -type f -name "gradlew" -printf "%h\n" \
                            | while read d; do
                                if [ -f "$d/app/build.gradle" ] || [ -f "$d/app/build.gradle.kts" ]; then
                                  echo "$d"
                                fi
                              done | sort -u)
          echo "Found projects:"
          printf ' - %s\n' "${PROJ[@]}"

          if [ "${#PROJ[@]}" -lt 2 ]; then
            echo "❌ 只找到 ${#PROJ[@]} 个 Android 工程，至少需要 2 个（手机端/车机端）。"
            exit 1
          fi

          echo "SENDER=${PROJ[0]}"   | tee -a $GITHUB_OUTPUT
          echo "RECEIVER=${PROJ[1]}" | tee -a $GITHUB_OUTPUT

      # 4) 规范化到固定目录
      - name: Normalize project folders
        run: |
          set -e
          rm -rf phone-caster car-receiver
          rsync -a "${{ steps.detect.outputs.SENDER }}/"   phone-caster/
          rsync -a "${{ steps.detect.outputs.RECEIVER }}/" car-receiver/
          echo "== phone-caster =="
          ls -la phone-caster | head -n 80
          echo "== car-receiver =="
          ls -la car-receiver | head -n 80

      # 5) 切换 Gradle 分发镜像并赋权 gradlew
      - name: Switch Gradle wrapper to CN mirror & chmod
        run: |
          set -e
          for f in phone-caster/gradle/wrapper/gradle-wrapper.properties car-receiver/gradle/wrapper/gradle-wrapper.properties; do
            if [ -f "$f" ]; then
              cp "$f" "$f.bak" || true
              # 镜像1：Gradle 中国镜像（默认）
              sed -i 's#https://services.gradle.org/distributions#https://downloads.gradle-dn.com/distributions#g' "$f"
              # 可切换镜像2：腾讯云（如上不稳就把上一行注释掉、放开下一行）
              # sed -i 's#https://services.gradle.org/distributions#https://mirrors.cloud.tencent.com/gradle#g' "$f"
              echo "---- $f ----"; tail -n +1 "$f"
            else
              echo "⚠️ 未找到 $f，跳过"
            fi
          done
          chmod +x phone-caster/gradlew || true
          chmod +x car-receiver/gradlew || true

      # 6) 编译两个工程（使用各自 wrapper）
      - name: Build phone-caster (debug)
        working-directory: phone-caster
        env:
          GRADLE_USER_HOME: ${{ github.workspace }}/.gradle-home
        run: ./gradlew --no-daemon --stacktrace assembleDebug

      - name: Build car-receiver (debug)
        working-directory: car-receiver
        env:
          GRADLE_USER_HOME: ${{ github.workspace }}/.gradle-home
        run: ./gradlew --no-daemon --stacktrace assembleDebug

      # 7) 收集 APK 打包
      - name: Collect APKs into a single ZIP
        run: |
          mkdir -p out
          cp phone-caster/app/build/outputs/apk/debug/*.apk out/phone-caster-debug.apk || true
          cp car-receiver/app/build/outputs/apk/debug/*.apk out/car-receiver-debug.apk || true
          (cd out && zip -9 -r apks.zip . && ls -la)

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: apks
          path: out/apks.zip
