name: Build phone-caster & car-receiver APKs
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Unzip project from repo ZIP
        run: |
          mkdir -p phone-caster car-receiver
          unzip -q ScreenCastProject_fixed_final.zip -d srczip
          PHONE_DIR=$(find srczip -type d -name "phone-caster" | head -n1 || true)
          CAR_DIR=$(find srczip -type d -name "car-receiver" | head -n1 || true)
          if [ -z "$PHONE_DIR" ] || [ -z "$CAR_DIR" ]; then
            echo "❌ 没找到 phone-caster / car-receiver 目录，请确认 ZIP 内结构"; exit 1
          fi
          rsync -a "$PHONE_DIR"/ phone-caster/
          rsync -a "$CAR_DIR"/ car-receiver/
          ls -la phone-caster car-receiver

      # 改 wrapper 的分发地址到国内镜像，然后给 gradlew 可执行权限
      - name: Switch Gradle wrapper to CN mirror & chmod
        run: |
          for f in phone-caster/gradle/wrapper/gradle-wrapper.properties car-receiver/gradle/wrapper/gradle-wrapper.properties; do
            cp "$f" "$f.bak" || true
            # 方案1：Gradle 中国镜像
            sed -i 's#https://services.gradle.org/distributions#https://downloads.gradle-dn.com/distributions#g' "$f"
            # 如需改用腾讯云镜像，换成这一行：
            # sed -i 's#https://services.gradle.org/distributions#https://mirrors.cloud.tencent.com/gradle#g' "$f"
            echo "---- $f ----"; cat "$f"
          done
          chmod +x phone-caster/gradlew || true
          chmod +x car-receiver/gradlew || true

      - name: Build phone-caster (debug)
        working-directory: phone-caster
        env:
          GRADLE_USER_HOME: ${{ github.workspace }}/.gradle-home
        run: ./gradlew --no-daemon --stacktrace assembleDebug

      - name: Build car-receiver (debug)
        working-directory: car-receiver
        env:
          GRADLE_USER_HOME: ${{ github.workspace }}/.gradle-home
        run: ./gradlew --no-daemon --stacktrace assembleDebug

      - name: Collect APKs into a single ZIP
        run: |
          mkdir -p out
          cp phone-caster/app/build/outputs/apk/debug/*.apk out/phone-caster-debug.apk || true
          cp car-receiver/app/build/outputs/apk/debug/*.apk out/car-receiver-debug.apk || true
          (cd out && zip -9 -r apks.zip .)

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: apks
          path: out/apks.zip
